<div class="Fahim-info">
    <h4 style="margin:0;">
        This is a product of Fahim.
        You can visit our
        <a target="_blank" style="text-decoration:none;" href="https://Fahim.com">
            website
        </a>
        or follow us on
        <a target="_blank" style="text-decoration:none;" href="https://twitter.com/_Fahim">
            Twitter
        </a>
        for updates about new extension releases.
    </h4>
</div>
